DROP TABLE IF EXISTS urls;

create table urls (
                      id         bigint generated by default as identity not null,
                      name       varchar(255),
                      created_at timestamp                               not null
);

DROP TABLE IF EXISTS url_checks;

create table url_checks (
                            id          bigint generated by default as identity not null,
                            status_code integer                                 not null,
                            title       varchar(255),
                            h1          varchar(255),
                            description text,
                            created_at  timestamp                               not null,
                            url_id      bigint                                  not null
);